###########################################
#################### DEV ##################
###########################################
stages:
  - stage: Deploy_Dev
    displayName: "Deploy to Dev Environment"
    variables:
      - template: parameters/envVariables.yml
        parameters:
            deploymentEnvironment: 'dev'
    jobs:
      - deployment: deploy
        displayName: 'Infrastructure deploy - dev '
        pool:
          vmImage: 'windows-latest'
        timeoutInMinutes: 180
        environment: ${{ variables.DO_ENV }}
        strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self
                  - task: AzurePowerShell@5
                    displayName: 'Deploy Bicep Template'
                    inputs:
                      azureSubscription: ${{ variables.SERVICE_CONNECTION }}
                      ScriptType: 'FilePath'
                      ScriptPath: '$(System.DefaultWorkingDirectory)/bicep/scripts/deploy-main.ps1'
                      azurePowerShellVersion: 'LatestVersion'
                      pwsh: true

###########################################
################### PROD ##################
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'Release-v') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      variables:
        - template: parameters/envVariables.yml
          parameters:
            deploymentEnvironment: 'prod'
      jobs:
        - deployment: deploy
          displayName: 'Infrastructure deploy - prod '
          pool:
            vmImage: 'windows-latest'
          timeoutInMinutes: 180
          environment: ${{ variables.DO_ENV }}
          strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: AzurePowerShell@5
                      displayName: 'Deploy Bicep Template'
                      inputs:
                        azureSubscription: ${{ variables.SERVICE_CONNECTION }}
                        ScriptType: 'FilePath'
                        ScriptPath: '$(System.DefaultWorkingDirectory)/bicep/scripts/deploy-main.ps1'
                        azurePowerShellVersion: 'LatestVersion'
                        pwsh: true