###########################################
#################### DEV ##################
###########################################
stages:
  - stage: Deploy_Dev
    displayName: "Deploy to Dev Environment"
    variables:
      - template: parameters/dev.parameters.yml
    jobs:
      - template: release.yml
        parameters:
          doEnvironment: ${{ variables.DO_ENV }}
          serviceConnection: ${{ variables.SERVICE_CONNECTION }}

###########################################
################### PROD ##################
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'Release-v') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      variables:
        - template: parameters/prod.parameters.yml
      jobs:
        - template: release.yml
          parameters:
            doEnvironment: ${{ variables.DO_ENV }}
            serviceConnection: ${{ variables.SERVICE_CONNECTION }} 