###########################################
#################### DEV ##################
###########################################
stages:
  - stage: Deploy_Dev
    displayName: "Deploy to Dev Environment"
    variables:
      - template: parameters/pipeline.parameters.yml
        parameters:
            deploymentEnvironment: 'dev'
    jobs:
      - template: release.yml
        parameters:
          adoEnvironment: ${{ variables.DO_ENV }}
          deploymentEnvironment: 'dev'
          serviceConnection: ${{ variables.SERVICE_CONNECTION }}

###########################################
################### PROD ##################
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'Release-v') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      variables:
        - template: parameters/pipeline.parameters.yml
          parameters:
            deploymentEnvironment: 'prod'
      jobs:
        - template: release.yml
          parameters:
            adoEnvironment: ${{ variables.DO_ENV }}
            deploymentEnvironment: 'prod'
            serviceConnection: ${{ variables.SERVICE_CONNECTION }}