parameters:
- name: 'serviceConnection'
  default: ''
- name: 'doEnvironment'
  default: ''

jobs:
- deployment: deploy
  displayName: Infrastructure deploy
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 180
  environment: ${{ parameters.doEnvironment }} 
  strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create \
                  --parameters resourceGroupName=rg-mballon \
                  --location eastus \
                  --template-file main.bicep