parameters:
- name: 'serviceConnection'
  default: ''
- name: 'doEnvironment'
  default: ''

jobs:
- deployment: deploy
  displayName: Infrastructure deploy
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 180
  environment: ${{ parameters.doEnvironment }} 
  strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              displayName: 'Check Bicep version'
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  bicep --version || echo "Bicep CLI not found"
#            - task: AzureCLI@2
#              inputs:
#                azureSubscription: '${{ parameters.serviceConnection }}'
#                scriptType: 'bash'
#                scriptLocation: 'inlineScript'
#               inlineScript: |
#                 az deployment sub create \
#                 --location eastus \
#                  --template-file "$(System.DefaultWorkingDirectory)"/bicep/main.bicep \
#                  --parameters @"$(System.DefaultWorkingDirectory)"/bicep/parameters/common.bicepparam