parameters:
- name: 'serviceConnection'
  default: ''
- name: 'doEnvironment'
  default: ''

jobs:
- deployment: deploy
  displayName: Infrastructure deploy
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 180
  environment: ${{ parameters.doEnvironment }} 
  strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              displayName: 'Build .bicepparam to .json'
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Building bicep param file..."
                  bicep build-params "$(System.DefaultWorkingDirectory)/bicep/parameters/common.bicepparam"

                  echo "Generated parameter file:"
                  ls "$(System.DefaultWorkingDirectory)/bicep/parameters/common.bicepparam.json"