parameters:
- name: 'adoEnvironment'
  default: ''
  displayName: Name of the DevOps environment for approvals (sc-dev or sc-prod)
- name: deploymentEnvironment
  default: ''
  displayName: Actual target environment used in Bicep (dev or prod)
- name: 'serviceConnection'
  default: 'Azure Subscription Service Connection'

jobs:
- deployment: deploy
  displayName: Infrastructure deploy
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 180
  environment: ${{ parameters.adoEnvironment }} 
  strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              displayName: 'Build .bicepparam to .json'
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Building bicep param file..."
                  bicep build-params "$(System.DefaultWorkingDirectory)/bicep/parameters/common.bicepparam" \
                  --outfile "$(System.DefaultWorkingDirectory)"/bicep/parameters/main.${{ parameters.deploymentEnvironment }}.bicepparam.json

                  echo "Generated parameter file:"
                  ls "$(System.DefaultWorkingDirectory)"/bicep/parameters/
            - task: AzureCLI@2
              displayName: 'Deploy Bicep Template'
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create \
                  --location eastus \
                  --template-file "$(System.DefaultWorkingDirectory)"/bicep/main.bicep \
                  --parameters @"$(System.DefaultWorkingDirectory)"/bicep/parameters/main.${{ parameters.deploymentEnvironment }}.bicepparam.json