###########################################
####                 DEV               ####
###########################################
stages:
  - stage: Deploy_NonProd
    displayName: "Deploy to Non-Prod Environment"
    jobs:
      - template: release.yml
        parameters:
          adoEnvironment: 'sc-dev'
          deploymentEnvironment: 'nonProd'
          modulePath: $(ModulePath)
          serviceConnection: 'Infra-Bicep' # 'AzureServiceConnection-nonProd'

###########################################
####                 PROD              ####
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'branch-v') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      jobs:
        - template: release.yml
          parameters:
            adoEnvironment: 'schs-prod'
            deploymentEnvironment: 'Prod' # The DevOps Environment with optional built-in Approval Gates
            modulePath: $(ModulePath)
            serviceConnection: 'AzureServiceConnection-Prod'