###########################################
####                 DEV               ####
###########################################
stages:
  - stage: Deploy_NonProd
    displayName: "Deploy to Non-Prod Environment"
    jobs:
      - template: release.yml
        parameters:
          adoEnvironment: 'schs-dev'
          deploymentEnvironment: 'nonProd'
          region: $(DeploymentRegion)
          serviceConnection: 'AzureServiceConnection-nonProd'

###########################################
####                 PROD              ####
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'main') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      jobs:
        - template: release.yml
          parameters:
            adoEnvironment: 'schs-dev'
            deploymentEnvironment: 'Prod' # The DevOps Environment with optional built-in Approval Gates    
            region: $(DeploymentRegion)
            serviceConnection: 'AzureServiceConnection-Prod'