variables:
  - name: DeploymentRegion
    value: '' # Default region for deployments

###########################################
####                 DEV               ####
###########################################
stages:
  - stage: Deploy_NonProd
    displayName: "Deploy to Non-Prod Environment"
    jobs:
      - template: release.yml
        parameters:
          adoEnvironment: 'sc-dev'
          deploymentEnvironment: 'non-prod'
          region: ${{ variables.DeploymentRegion }}
          serviceConnection: 'Infra-Bicep'

###########################################
####                 PROD              ####
###########################################
  - ${{ if contains(variables['Build.SourceBranch'], 'Branch-v') }}:
    - stage: Deploy_Prod
      displayName: "Deploy to Prod Environment"
      jobs:
        - template: release.yml
          parameters:
            adoEnvironment: 'Prod'
            deploymentEnvironment: 'prod' # The DevOps Environment with optional built-in Approval Gates    
            region: ${{ variables.DeploymentRegion }}
            serviceConnection: 'Infra-Bicep' # Update to AzureServiceConnection-Non-Prod 